const fs = require('fs');
const path = require('path');

const DOCS_DIR = path.resolve(__dirname, '../../../docs');
const OUTPUT_FILE = path.resolve(__dirname, '../lib/docs-db.ts');

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\.md$/, '')
    .replace(/_/g, '-');
}

function extractHeadings(content) {
  const lines = content.split('\n');
  const headings = [];
  lines.forEach(line => {
    if (line.startsWith('## ')) {
      const label = line.substring(3).trim();
      const id = label.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      headings.push({ id, label });
    }
  });
  return headings;
}

function parseFile(dirPath, fileName, category) {
  const filePath = path.join(dirPath, fileName);
  const rawContent = fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');

  // Find the first # title
  const lines = rawContent.split('\n');
  let title = '';
  let description = '';
  let contentStartIndex = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('# ')) {
      title = line.substring(2).trim();
      contentStartIndex = i + 1;
      break;
    }
  }

  // Extract first paragraph as description
  for (let i = contentStartIndex; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line && !line.startsWith('#') && !line.startsWith('-') && !line.startsWith('`')) {
      description = line;
      break;
    }
  }

  // Clean description of markdown formatting
  description = description
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .substring(0, 120) + '...';

  const id = slugify(fileName);
  const headings = extractHeadings(rawContent);

  // Content starts after title
  const content = lines.slice(contentStartIndex).join('\n').trim();

  return {
    id,
    category,
    title: title || id,
    subtitle: description || 'Technical Documentation Guide',
    description: `Wyre technical guide for ${title || id}.`,
    headings,
    content
  };
}

function run() {
  console.log('Compiling docs...');
  const getStartedDir = path.join(DOCS_DIR, 'getting_started');
  const coreDir = path.join(DOCS_DIR, 'core');
  const streamingDir = path.join(DOCS_DIR, 'streaming');

  const articles = [];

  if (fs.existsSync(getStartedDir)) {
    const files = fs.readdirSync(getStartedDir).filter(f => f.endsWith('.md'));
    // Ensure overview.md is first in the list
    files.sort((a, b) => {
      if (a === 'overview.md') return -1;
      if (b === 'overview.md') return 1;
      return a.localeCompare(b);
    });
    files.forEach(f => {
      articles.push(parseFile(getStartedDir, f, 'GETTING STARTED'));
    });
  }

  if (fs.existsSync(coreDir)) {
    const files = fs.readdirSync(coreDir).filter(f => f.endsWith('.md'));
    files.forEach(f => {
      articles.push(parseFile(coreDir, f, 'CORE ARCHITECTURE'));
    });
  }

  if (fs.existsSync(streamingDir)) {
    const files = fs.readdirSync(streamingDir).filter(f => f.endsWith('.md'));
    files.forEach(f => {
      articles.push(parseFile(streamingDir, f, 'STREAMING & ISOLATION'));
    });
  }

  // Ensure output directory exists
  const libDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true });
  }

  const outputContent = `// Automatically generated by compile-docs.js. Do not edit directly.

export interface DocArticle {
  id: string;
  category: string;
  title: string;
  subtitle: string;
  description: string;
  headings: { id: string; label: string }[];
  content: string;
}

export const articles: DocArticle[] = ${JSON.stringify(articles, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, outputContent, 'utf8');
  console.log(`Successfully compiled ${articles.length} articles to ${OUTPUT_FILE}`);
}

run();
